version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    ports:
      - 8000:80
    volumes:
        - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public