version: '3.8'
services:
  apache:
    build:
      context: .
      dockerfile: docker/Dockerfile
    labels: 
      - "traefik.http.routers.apache.rule=Host(`vivaairva.com`)"
      - "traefik.http.routers.apache.entrypoints=websecurity"
      - "traefik.http.routers.apache.tls.certresolver=myresolver"
    #volumes: 
      #- ./php/:/var/www/html
    networks: 
      traefik_network:
networks: 
  traefik_network:
    name: traefik_net
    driver: bridge
