version: '3.8'
services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: vivaairva-app
    networks:
      - titacticos_net


  servicio:
        image: 'nginx:alpine'
        container_name: vivaairva-webserver        
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8014:8000'
        labels:
          # Explicitly tell Traefik to expose this container
          - "traefik.enable=true"
          # The domain the service will respond to
          - "traefik.http.services.servicio.loadbalancer.server.port=80"
          - "traefik.http.routers.servicio.rule=Host(`vivaairva.com`)"
          - "traefik.http.routers.servicio.entrypoints=websecure"
          - "traefik.http.routers.servicio.tls.certresolver=myresolver"
          - "traefik.http.routers.servicio.tls=true"
        networks:
          - titacticos_net
          
networks:
  titacticos_net:
   external: true
