version: '3.8'
services:
  viva:
    build:
      context: .
      dockerfile: docker/Dockerfile
    labels: 
      - "traefik.http.routers.viva.rule=Host(`vivaairva.com`)"
      - "traefik.http.routers.viva.entrypoints=websecurity"
      - "traefik.http.routers.viva.tls.certresolver=myresolver"
    #volumes: 
      #- ./php/:/var/www/html
    networks: 
      traefik_network:
networks: 
  traefik_network:
    name: traefik_net
    driver: bridge
    ipam: 
      driver: default