version: '3.8'
services:
  vivaapp:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: vivaairva-app
    labels:
      - "traefik.http.routers.vivaapp.rule=Host(`vivaairva.com`)"
      - "traefik.http.services.laravel.loadbalancer.server.port=9000"
    networks:
      - titacticos_net
    expose:
      - "9000"

networks:
  titacticos_net:
   external: true
