version: '3.8'
services:
  vivaapp:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: vivaairva-app
    labels:
      - "traefik.http.routers.vivaapp.rule=Host(`vivaairva.com`)"
    networks:
      - titacticos_net

networks:
  titacticos_net:
   external: true
