###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:

    control-bridge-app:
        image: 'nginx:alpine'
        container_name: control-bridge-webserver        
        working_dir: /application
        volumes:
            - '.:/application'
            - './laravel-docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8010:8000'
        labels:
          # Explicitly tell Traefik to expose this container
          - "traefik.enable=true"
          # The domain the service will respond to
          - "traefik.http.services.control-bridge-app.loadbalancer.server.port=80"
          - "traefik.http.routers.control-bridge-app.rule=Host(`control-bridge.emision.dev`)"
          - "traefik.http.routers.control-bridge-app.entrypoints=websecure"
          - "traefik.http.routers.control-bridge-app.tls.certresolver=myresolver"
          - "traefik.http.routers.control-bridge-app.tls=true"
        networks:
          - traefik_proxy_net        

    php-fpm:
        build: laravel-docker/php-fpm
        container_name: control-bridge-app
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
        networks:
          - traefik_proxy_net
networks:
  traefik_proxy_net:
    external: true